server:
  port: 80

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer默认为true
    fetchRegistry: true        #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7002.com:7002/eureka #集群版

spring:
  application:
    name: cloud-order-service