server:
 port: 3344
spring:
 application:
  name: cloud-config-center
 cloud:
  config:
   server:
    git:
     uri: https://github.com/songhaiboGitHub/SpringClouOnAlibabaConfig.git    #填写你自己的github路径
     search-paths:
      - SpringClouOnAlibabaConfig
   label: master
eureka:
 client:
  service-url:
   defaultZone: http://localhost:7001/eureka


rabbitmq:
 host: localhost
 port: 15672
 username: guest
 password: guest

#暴露bus端点
management:
 endpoints:
  web:
   exposure:
    include: 'bus-refresh'